### PR TITLE
Change license from LGPL to MIT/Apache2.0

### PR DESCRIPTION
**Pull request by AaronErhardt**
This makes sense since this is just a macro anyway and Relm4 already uses MIT/Apache2.0.

@tronta do you agree with these changes? Any of your submissions will also fall under the new licenses.

### CODE REVIEW

**Comment by tronta** [comment]
Sure. No Problem. Anything I should do?

**Comment by AaronErhardt** [comment]
No, I think I only need the confirmation by @N4tus for this. I will take care of the rest :)

**Comment by tronta** [comment]
Thank you so much for your effort. I really appreciate your work!

**Comment by AaronErhardt** [comment]
@n4tus is it ok for you if I change the license to Apache/MIT? This would also affect code submitted as part of your contribution.

**Comment by N4tus** [comment]
Yes, I am fine with a change of the license to Apache/MIT.

**Comment by AaronErhardt** [comment]
Thanks!

**Pull request merged**
